# Generated by Django 5.0.2 on 2023-11-21 21:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to=accounts.models.avatar_path),
        ),
    ]
