# Generated by Django 5.0.2 on 2024-02-17 19:50

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.URLField(default=uuid.uuid4, editable=False, unique=True)),
                ('school_id', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('4000', '400')], max_length=200)),
                ('avatar', models.FileField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.avatar_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
