# Generated by Django 5.0.2 on 2024-02-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
