# Generated by Django 5.0.2 on 2024-02-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
