# Generated by Django 5.0.2 on 2024-02-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_id',
            field=models.CharField(default=True, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
