# Generated by Django 5.0.2 on 2024-02-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], max_length=255, null=True),
        ),
    ]
