# Generated by Django 5.0.2 on 2024-02-26 00:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_account_type_user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.avatar_path),
        ),
    ]
