# Generated by Django 5.0.2 on 2024-02-26 01:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_avatar_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=accounts.models.avatar_path),
        ),
    ]
