# Generated by Django 5.0.2 on 2024-03-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_avatar_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=99999, null=True),
        ),
    ]
