# Generated by Django 5.0.2 on 2024-02-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_room_room_password_room_room_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], max_length=255, null=True),
        ),
    ]
