# Generated by Django 5.0.2 on 2024-02-28 01:25

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_room_room_password_alter_room_room_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_avatar',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=classroom.models.avatar_directory_path),
        ),
    ]
