# Generated by Django 5.0.2 on 2024-03-02 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
