# Generated by Django 5.0.2 on 2024-03-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_message_message_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
    ]
