# Generated by Django 5.0.2 on 2023-11-21 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='room',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.room'),
            preserve_default=False,
        ),
    ]
