# Generated by Django 5.0.2 on 2023-11-21 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_resources_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
        migrations.AddField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(related_name='resources', to='classroom.resource'),
        ),
    ]
