# Generated by Django 5.0.2 on 2023-11-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_rename_resources_resource_room_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='room',
        ),
    ]
