# Generated by Django 5.0.2 on 2024-03-02 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0017_remove_resource_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
