# Generated by Django 5.0.2 on 2024-03-05 18:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_resource_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
