# Generated by Django 5.0.2 on 2024-03-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_alter_message_message_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, related_name='resources', to='classroom.resource'),
        ),
    ]
