# Generated by Django 5.0.2 on 2024-03-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0021_alter_room_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='resources', to='classroom.resource'),
        ),
    ]
