# Generated by Django 5.0.2 on 2024-04-05 13:35

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_alter_room_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=classroom.models.resources_image_path),
        ),
    ]
