# Generated by Django 5.0.2 on 2024-04-05 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_studyai'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyai',
            options={'verbose_name_plural': 'StudyAI'},
        ),
        migrations.AddField(
            model_name='studyai',
            name='ai_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
